[package]

name = "marpa-sys"
version = "0.0.1"
description = "Bindings for libmarpa"
build = "build.rs"
links = "marpa"

[lib]
name = "marpa_sys"

[build-dependencies]
pkg-config = "0.3"
gcc = "0.3"

[dependencies]
libc = "*"
